# GoReleaser configuration for MOTD
# https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are tidy
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: motd
    binary: motd
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.VERSION={{.Version}}
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm

  # Separate Windows build to allow for UPX compression
  - id: motd-windows
    binary: motd
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.VERSION={{.Version}}
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - AGENT.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  name_template: "v{{.Version}}"
  prerelease: auto
  mode: replace
  draft: false
  header: |
    ## MOTD {{.Version}} Release

    Fast, lightweight system information display for Linux/Unix systems.

    ### Installation

    **Linux/macOS:**
    ```bash
    # Download the appropriate binary for your system
    # Extract and move to /usr/local/bin
    tar -xzf motd_{{.Version}}_Linux_x86_64.tar.gz
    sudo mv motd /usr/local/bin/
    ```

    **Windows:**
    ```powershell
    # Extract the zip file and add to PATH
    ```

    ### What's Changed
  footer: |
    ---
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Performance
    - Startup time: ~10-50ms
    - Memory usage: ~5-10MB
    - Binary size: ~2-3MB (optimized)

# Announce releases (optional - uncomment if you want)
# announce:
#   discord:
#     enabled: true
#     message_template: 'MOTD {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'
