#!/bin/bash
# Quick commands for working with the Go MOTD implementation

echo "MOTD Go Implementation - Quick Reference"
echo "========================================"
echo ""
echo "Quick Commands:"
echo "---------------"
echo ""
echo "# Build the binary"
echo "make build-optimized"
echo ""
echo "# Run the binary"
echo "./bin/motd"
echo ""
echo "# Show help"
echo "./bin/motd -h"
echo ""
echo "# Show version"
echo "./bin/motd -v"
echo ""
echo "# Enable debug mode"
echo "./bin/motd -d"
echo ""
echo "# Install system-wide"
echo "sudo make install"
echo ""
echo "# Cross-compile for other platforms"
echo "make cross-compile"
echo ""
echo "# Clean build artifacts"
echo "make clean"
echo ""
echo "# Run tests"
echo "make test"
echo ""
echo "Key Files:"
echo "----------"
echo "  main.go                - Source code"
echo "  bin/motd               - Compiled binary (output directory)"
echo "  Makefile               - Build automation"
echo "  README.md              - Full documentation"
echo "  REFACTORING_SUMMARY.md - Technical details"
echo "  AGENT.md               - Development guidelines"
echo ""
echo "Performance:"
echo "------------"
echo "  Startup time: ~10-50ms"
echo "  Memory usage: ~5-10MB"
echo "  Binary size:  ~6MB (optimized)"
echo ""
